### ISSUE TITLE
Latest tagged version doesn't match published RubyGem

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-ruby#173]
## Summary
The latest published gem is [5.3.2](https://rubygems.org/gems/conjur-api/versions/5.3.2) from May 6. The version of the gem is consistent with the [latest version bump](https://github.com/cyberark/conjur-api-ruby/commit/0df9c34990ae72e94d560e61ce73abc21e640631) from January 10, but it wasn't published on January 10 - and there are no commits in the project from May 6.

## Expected Results
Gems are only published when the repo is tagged

## Actual Results (including error logs, if applicable)
A gem was published without a tag

## Additional Information
To address this, we should update the pipeline to publish on tag-triggered builds and ensure the CONTRIBUTING is clear that to release a new gem, you should add a tag to the project.

**Comment by JakeQuilty** [comment]
## Details

The current requirements for publishing to RubyGems are:
* Branch = 'master'
* "AND someone confirms this stage within 5 minutes"

The way it checks for "someone confirming" the publishing was by checking the env variable `PUBLISH_GEM == true`. So, any merge into `master` with the env var `PUBLISH_GEM` set to true would publish a version to RubyGems.

The `publish.sh` script grabs the version from `lib/conjur-api/version.rb`

## Issue

Currently:
* RubyGems version = `5.3.2`
* [`lib/conjur-api/version.rb`](https://github.com/cyberark/conjur-api-ruby/commit/0df9c34990ae72e94d560e61ce73abc21e640631) = `5.3.2`
* [Most Recent Tag](https://github.com/cyberark/conjur-api-ruby/tags) = `5.3.1`

It looks like when the version was bumped on Jan 10th the check for someone setting the env variable didn't get done, so the version was not published to RubyGems on that day.

Unfortunately [Jenkins history](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur-api-ruby/activity/?branch=master) doesn't go back that far, but on May 6 the `Jenkinsfile` must have ran on master with the `PUBLISH_GEM` env variable set to true. This was probably someone realizing the `5.3.2` version was never published in January OR an accidental re-publish over the `5.3.2` version from Jan 10. I'm waiting to get access to more detail on RubyGems.org to see if there's any more info on this.

## Planned Solution

* Update the Jenkinsfile to publish on a tagged release how [Secretless checks](https://github.com/cyberark/secretless-broker/blob/e9ee1effce706acb16f3c4e4c60a55c849477ce2/Jenkinsfile#L179)
* Create a `5.3.2` tag so the current tag matches the current version

**Comment by izgeri** [comment]
Thanks @JakeQuilty! Given the way that our publishing has progressed in other projects, I think it makes sense that a new tag is effectively a user saying "it's ok to publish" - so an additional `PUBLISH_GEM` step should not be required.

I appreciate your detailed notes! :)
