### ISSUE TITLE
Ruby client uses basic authentication for API key rotation events

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-api-ruby#181]
## Summary

Nightly builds have started to fail in our CI/CD pipelines and the error is reproducible locally.

Errors are:
- [ ] `cucumber features/host.feature:14 # Scenario: API key of a a host can be rotated.`
- [ ] `SimpleCov failed with exit 1Coverage report generated for Cucumber Features, RSpec to /src/conjur-api/coverage/coverage.xml. 1415 / 1538 LOC (92.0%) covered.`

## Steps to Reproduce

1. Check out repo locally
2. Run `./test.sh`

## Expected Results
Passing tests

## Actual Results (including error logs, if applicable)
Tests fail

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
[Latest](https://github.com/cyberark/conjur-api-ruby/commit/a0b2be4b6abdc3077a556fea667a0d5f66f35fbc)

## Environment setup
Jenkins and local macOS env

## Additional Information
The problem may have been caused by server behavior change in regards to rotation of API keys that can be found [here](https://github.com/cyberark/conjur/pull/1884/files).

**Comment by izgeri** [comment]
Note: this is likely related to changes made in the v1.9.0 release of Conjur.

It would be good to understand whether other clients are also impacted, but may not have appropriate test coverage to catch the issue.

**Comment by sgnn7** [comment]
@izgeri So far:
- Golang: [Has tests](https://github.com/cyberark/conjur-api-go/blob/692f507ef14fe2e7f469e7b83f193fd3e9a770f8/conjurapi/authn_test.go#L35-L58). Unknown how they relate to the code change.
- Python3: Doesn't support rotation of key
- Java: Doesn't seem to support rotation of key
- .NET: Doesn't seem to support rotation of key
- Powershell: Java: Doesn't seem to support rotation of key
- JS: N/A

**Comment by izgeri** [comment]
Noting that an issue was discovered in Conjur CLI, that appears to be related since the CLI uses this Ruby library.

**Comment by sgnn7** [comment]
Closing via #182
