### ISSUE TITLE
There is a new release of the Ruby client including a fix for API key rotation

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-ruby#182]
Following the release of Conjur v1.9.0 (DAP 11.7+) which included a [medium security bug fix](https://github.com/cyberark/conjur/security/advisories/GHSA-qhjf-g9gm-64jq), the methods for API key rotation need to be updated to ensure they follow the new guidelines.

This should be fixed in the Ruby client in #181, and once those changes are in we will need a new release.

AC:
- [ ] There is a new release of the Ruby client including the fixes from #181

**Comment by sgnn7** [comment]
Release [v5.3.4](https://rubygems.org/gems/conjur-api/versions/5.3.4) published. Closing.
